// Generated by gencpp from file beginner_tutorials/Fun_xyzResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_FUN_XYZRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_FUN_XYZRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Fun_xyzResponse_
{
  typedef Fun_xyzResponse_<ContainerAllocator> Type;

  Fun_xyzResponse_()
    : s(0)  {
    }
  Fun_xyzResponse_(const ContainerAllocator& _alloc)
    : s(0)  {
  (void)_alloc;
    }



   typedef int64_t _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Fun_xyzResponse_

typedef ::beginner_tutorials::Fun_xyzResponse_<std::allocator<void> > Fun_xyzResponse;

typedef boost::shared_ptr< ::beginner_tutorials::Fun_xyzResponse > Fun_xyzResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::Fun_xyzResponse const> Fun_xyzResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/felix/dianracing_driverless_recruiting/lizhuofan1752657/dianracing_ros_lizhuofan/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "304c92b24150f0692f4ca17cca2b0719";
  }

  static const char* value(const ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x304c92b24150f069ULL;
  static const uint64_t static_value2 = 0x2f4ca17cca2b0719ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Fun_xyzResponse";
  }

  static const char* value(const ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 s\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fun_xyzResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Fun_xyzResponse_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<int64_t>::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_FUN_XYZRESPONSE_H
