// Generated by gencpp from file beginner_tutorials/Fun_xyz.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_FUN_XYZ_H
#define BEGINNER_TUTORIALS_MESSAGE_FUN_XYZ_H

#include <ros/service_traits.h>


#include <beginner_tutorials/Fun_xyzRequest.h>
#include <beginner_tutorials/Fun_xyzResponse.h>


namespace beginner_tutorials
{

struct Fun_xyz
{

typedef Fun_xyzRequest Request;
typedef Fun_xyzResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Fun_xyz
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Fun_xyz > {
  static const char* value()
  {
    return "eaeadefa75cc1dc5d7db7aada9ebc9b2";
  }

  static const char* value(const ::beginner_tutorials::Fun_xyz&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Fun_xyz > {
  static const char* value()
  {
    return "beginner_tutorials/Fun_xyz";
  }

  static const char* value(const ::beginner_tutorials::Fun_xyz&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::Fun_xyzRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Fun_xyz > 
template<>
struct MD5Sum< ::beginner_tutorials::Fun_xyzRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Fun_xyz >::value();
  }
  static const char* value(const ::beginner_tutorials::Fun_xyzRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::Fun_xyzRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Fun_xyz > 
template<>
struct DataType< ::beginner_tutorials::Fun_xyzRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Fun_xyz >::value();
  }
  static const char* value(const ::beginner_tutorials::Fun_xyzRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::Fun_xyzResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Fun_xyz > 
template<>
struct MD5Sum< ::beginner_tutorials::Fun_xyzResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Fun_xyz >::value();
  }
  static const char* value(const ::beginner_tutorials::Fun_xyzResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::Fun_xyzResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Fun_xyz > 
template<>
struct DataType< ::beginner_tutorials::Fun_xyzResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Fun_xyz >::value();
  }
  static const char* value(const ::beginner_tutorials::Fun_xyzResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_FUN_XYZ_H
